# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "task-esemble-app"

[default.build]
[default.build.parameters]
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "task-ensemble-app"
s3_prefix = "task-ensemble-app"
region = "us-east-1"
profile = "moreseconds"
image_repositories = ["TaskFunction=950711849260.dkr.ecr.us-east-1.amazonaws.com/taskensembleappd36b7729/taskfunction7f1becfbrepo"]

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
